lowercaseOutputName: true
rules:
# Kafka Connect Worker Metrics
- pattern: "kafka.connect<type=connect-worker-metrics>([^:]+):"
  name: "kafka_connect_worker_metrics_$1"
# Debezium Connector Metrics (Postgres)
- pattern: "debezium.postgres<type=connector-metrics, context=([^,]+), server=([^>]+)>([^:]+):"
  name: "debezium_metrics_$3"
  labels:
    context: "$1"
    server: "$2"
# Standard JVM Metrics
- pattern: "java.lang<type=Memory><>HeapMemoryUsage"
  name: "jvm_memory_heap_usage"