---
global:
  scrape_interval: 5s
  scrape_native_histograms: true

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: kafka
    static_configs:
      - targets: ["kafka:9405"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: phoenix-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["phoenix-backend:8080"]

# Keep Prometheus v3 OTLP receiver enabled in LGTM
otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment # backward compatibility
    - deployment.environment.name
    - k8s.cluster.name
    - k8s.container.name
    - k8s.cronjob.name
    - k8s.daemonset.name
    - k8s.deployment.name
    - k8s.job.name
    - k8s.namespace.name
    - k8s.node.name
    - k8s.pod.name
    - k8s.replicaset.name
    - k8s.statefulset.name
    - host.name
    - postgresql.database.name
    - postgresql.schema.name
    - postgresql.table.name
    - postgresql.index.name
    - database
    - kafka.cluster.alias

storage:
  tsdb:
    out_of_order_time_window: 10m

